# Generated by Django 3.2.18 on 2023-06-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='media/pics')),
            ],
        ),
        migrations.CreateModel(
            name='Oneway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Mo_No', models.IntegerField()),
                ('FromCity', models.CharField(max_length=200)),
                ('Tocity', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('StartTime', models.TimeField()),
                ('CabChoice', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RoundTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mame', models.CharField(max_length=200)),
                ('mo_No', models.IntegerField()),
                ('fromCity', models.CharField(max_length=200)),
                ('toCity', models.CharField(max_length=200)),
                ('dateOfJourney', models.DateField()),
                ('dateOfReturn', models.DateField()),
                ('startTime', models.TimeField()),
                ('cabChoice', models.CharField(max_length=200)),
            ],
        ),
    ]
