# Generated by Django 3.2.18 on 2023-06-01 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roundtrip',
            old_name='mame',
            new_name='name',
        ),
    ]
