# Generated by Django 3.2.18 on 2023-06-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabApp', '0002_rename_mame_roundtrip_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PackageName', models.CharField(max_length=200)),
                ('Price', models.IntegerField()),
                ('CabType', models.CharField(max_length=200)),
            ],
        ),
    ]
